@startuml
title "Lab 2 - Running solution on machine"
node PC {
    node docker as DockerContainerBackend{
        artifact backend
    }
    node docker as DockerContainerFrontEnd1{
        artifact frontend_instance_1
    }
    node docker as DockerContainerFrontEnd2{
        artifact frontend_instance_2
    }
    node WebBroser1{
    }
    node WebBroser2{
    }
}

WebBroser1 --> frontend_instance_1: localhost:4001
WebBroser2 --> frontend_instance_2: localhost:4002

frontend_instance_1 --> backend: ws://localhost:4000
frontend_instance_2 --> backend: ws://localhost:4000

note left of frontend_instance_2
env var:
PORT 4002
REACT_APP_WS_PORT 4000
endnote

note bottom of backend
env:
PORT 4000
endnote

note right of frontend_instance_1
env var:
PORT 4001
REACT_APP_WS_PORT 4000
endnote


@enduml