apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
  labels:
    app: chat
spec:
  selector:
    matchLabels:
      app: test-backend
  replicas: 10
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
      - name: test-backend
        image: chat/test-backend:latest
        imagePullPolicy: Never
        env:
        - name: WS_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: chat-configs
              key: backend_domain
        - name: MESSAGE_DELAY
          valueFrom:
            configMapKeyRef:
              name: chat-configs
              key: test_delay
        - name: PORT
          value: "4000"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: test-backend
  labels:
    app: test-backend
spec:
  type: NodePort
  ports:
  - port: 4000
  selector:
    app: test-backend
