@startuml
title "Lab 4 - Running solution on Kubernetes"
node PC {

    node KuberentesCluster{

        node ingress as IngressFrontend{
        }

        node ingress as IngressBackend{
        }

        node service as ServiceFrontend{
        }

        node service as ServiceBackend{
        }

        node service as ServiceBroker{
        }

        node Node as MinikubeNode{
            node pod as BackendPod{
                node docker as BackendDocker{
                    artifact backend
                }
            }
            node pod as FrontendPod{
                node docker as FrontDocker{
                    artifact frontend
                }
            }
            node pod as RabbitMQPod {
                node docker as RabbitMQDocker{
                    artifact rabbitmq
                }
            }
        }
    }
}

IngressFrontend --> ServiceFrontend: send traffic
IngressBackend --> ServiceBackend: send traffic

ServiceBackend --> backend: conn
ServiceFrontend --> frontend:  conn
ServiceBroker --> rabbitmq: conn

frontend -> backend: ws://api.chat-test.com
backend -> rabbitmq: amqp://guest:gest@rabbitmq

note top of IngressBackend
Maps api.chat-test.com into service
endnote

note top of IngressFrontend
Maps chat-test.com into service
endnote


note bottom of backend
env:
PORT execution port

Use service name to talk to rabbitmq
endnote

note bottom of frontend
env var:
PORT execution port
REACT_APP_WS_DOMAIN WebSocket domain if any
endnote

@enduml
