@startuml kubernetes

footer Kubernetes Plant-UML
scale max 1024 width

skinparam nodesep 10
skinparam ranksep 10

' Kubernetes
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!includeurl KubernetesPuml/kubernetes_Common.puml
!includeurl KubernetesPuml/kubernetes_Context.puml
!includeurl KubernetesPuml/kubernetes_Simplified.puml

!includeurl KubernetesPuml/OSS/KubernetesSvc.puml
!includeurl KubernetesPuml/OSS/KubernetesIng.puml
!includeurl KubernetesPuml/OSS/KubernetesPod.puml
!includeurl KubernetesPuml/OSS/KubernetesRs.puml
!includeurl KubernetesPuml/OSS/KubernetesDeploy.puml
!includeurl KubernetesPuml/OSS/KubernetesHpa.puml
!includeurl KubernetesPuml/OSS/KubernetesNode.puml

actor "User" as userAlias
left to right direction

' Kubernetes Components
Cluster_Boundary(cluster, "Minikube-Kubernetes Cluster") {
    Namespace_Boundary(ns, "default") {
        KubernetesIng(ingress, "api.chat-test.com", "")
        KubernetesSvc(svc, "service backend", "")
        KubernetesPod(pod1, "Backend pod1", "")
        KubernetesPod(pod2, "Backend pod2", "")
        KubernetesPod(pod3, "Backend pod3", "")

        KubernetesIng(ingress2, "chat-test.com", "")
        KubernetesSvc(svc2, "service frontend", "")
        KubernetesPod(pod4, "Frontend pod1", "")
        KubernetesPod(pod5, "Frontend pod2", "")
        KubernetesPod(pod6, "Frontend pod3", "")

        KubernetesIng(ingress3, "rabbit.chat-test.com", "")
        KubernetesSvc(svc3, "service rabbit", "")
        KubernetesPod(pod7, "Rabbit MQ pod", "")
    }
}

Rel(userAlias, ingress," ")
Rel(ingress, svc, " ")
Rel(svc, pod1, " ")
Rel(svc, pod2, " ")
Rel(svc, pod3, " ")

Rel(userAlias, ingress2," ")
Rel(ingress2, svc2," ")
Rel(svc2, pod4," ")
Rel(svc2, pod5," ")
Rel(svc2, pod6," ")

Rel(userAlias, ingress3," ")
Rel(ingress3, svc3," ")
Rel(svc3, pod7," ")

@enduml
